version: 0.2

phases:
  install:
    commands:
      - echo Nada para executar em install phase...
  pre_build:
    commands:
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_TOKEN
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c9y1i6i4
  build:
    commands:
      - mvn install
      - docker build -t hello-app .
      - docker tag hello-app:latest public.ecr.aws/c9y1i6i4/hello-app:latest
  post_build:
    commands:
      - docker push public.ecr.aws/c9y1i6i4/hello-app:latest
artifacts:
  files:
    - 'target/*.jar'