version: 0.2

phases:
  install:
    commands:
      - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_TOKEN
  pre_build:
    commands:
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c9y1i6i4
  build:
    commands:
      - mvn install
      - docker build -t hello-app .
      - docker tag hello-app:latest public.ecr.aws/c9y1i6i4/hello-app:latest
  post_build:
    commands:
      - docker push public.ecr.aws/c9y1i6i4/hello-app:latest
artifacts:
  files:
    - 'target/spring-boot-complete-0.0.1-SNAPSHOT.jar'
    - 'appspec.yml'
    - 'scripts/**/*'